#!/sbin/openrc-run
# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="Grafana Tempo"
description="Grafana Tempo is a distributed tracing backend"
command="/opt/bin/tempo"
command_args="-config.file /etc/tempo.yml"
command_background="true"
pidfile="/var/run/${RC_SVCNAME}.pid"
output_logger="logger -p daemon.info -t ${SVCNAME}"
error_logger="logger -p daemon.error -t ${SVCNAME}"

depend() {
    after net
}
