#!/sbin/openrc-run
# Copyright 1999-2022 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

pidfile="/run/airflow/flower.pid"
command="/usr/bin/airflow"
command_args="celery flower ${AIRFLOW_ARGS}"
command_args_background="--daemon --pid ${pidfile}"
command_user="airflow:airflow"

depend() {
	use logger
	need net
}

start_pre() {
	checkpath -q -d -o ${command_user} -m 0755 "$(dirname "${pidfile}")" || return 1
}
