#!/sbin/openrc-run
# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="keepalive_exporter daemon"
description="Prometheus exporter for Keepalived metrics."
command="/usr/bin/keepalived_exporter"
output_log="/var/log/keepalived_exporter/keepalived_exporter.log"
error_log="/var/log/keepalived_exporter/keepalived_exporter.err.log"
start_stop_daemon_args="--background --user keepalived_exporter"

depend() {
    need net
}
