#!/sbin/openrc-run

description="Prometheus PostgreSQL exporter"
pidfile="/run/${SVCNAME}/${SVCNAME}.pid"
user="${USER}"

command="/usr/bin/${SVCNAME}"
command_args="--config /etc/postgresql_exporter/config.yaml"
command_background="true"
start_stop_daemon_args="--user ${user} --wait 1000 \
	--stdout /var/log/prometheus/${SVCNAME}.log \
	--stderr /var/log/prometheus/${SVCNAME}.log"

depend() {
	need net
	after net
}

start_pre() {
	checkpath -d -m 0755 -o "${user}" "${pidfile%/*}"
}
