#!/sbin/openrc-run
# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Apache Mesos is a computer cluster manager"
name="Mesos [agent]"
command="/usr/sbin/${RC_SVCNAME}"
command_args="${MESOS_AGENT_ARGS}"
command_background="true"
start_stop_daemon_args="--user ${MESOS_AGENT_USER} --group ${MESOS_AGENT_GROUP}"
pidfile="/var/run/${RC_SVCNAME}.pid"
output_log="${MESOS_AGENT_LOG_FILE}"
error_log="${MESOS_AGENT_LOG_FILE}"

depend() {
    use net
}

start_pre() {
    local MESOS_AGENT_LOG_DIR=$(dirname ${MESOS_AGENT_LOG_FILE})
    checkpath -m 0755 \
        -o "${MESOS_AGENT_USER}:${MESOS_AGENT_GROUP}" \
        -d "${MESOS_AGENT_LOG_DIR}"
    checkpath -m 0755 \
        -o "${MESOS_AGENT_USER}:${MESOS_AGENT_GROUP}" \
        -d "${MESOS_AGENT_WORK_DIR}"
}
