#!/sbin/openrc-run

export VM_storageDataPath="${VM_STORAGE_DATA_PATH:/var/lib/victoriametrics}"
export VM_retentionPeriod="${VM_RETENTION_PERIOD:1}"
export VM_tls="${VM_TLS}"
export VM_tlsCertFile="${VM_TLS_CERT_FILE}"
export VM_tlsKeyFile="${VM_TLS_KEY_FILE}"
export VM_graphiteListenAddr="${VM_GRAPHITE_LISTEN_ADDR}"

name="VictoriaMetrics"

pidfile="/run/${RC_SVCNAME}"

command="/usr/bin/victoriametrics"
command_args="-envflag.enable -envflag.prefix=VM_"
command_background=yes

output_log="/var/log/victoriametrics/${RC_SVCNAME}.log"
error_log="/var/log/victoriametrics/${RC_SVCNAME}-error.log"
output_log="${VM_LOG_FILE:-/var/log/victoriametrics/victoriametrics.log}"
error_log="${VM_LOG_FILE:-/var/log/victoriametrics/victoriametrics-error.log}"

depend() {
	need local
	use net
}

start_pre() {
	checkpath -d -m 0755 -o "${command_user}" $(dirname ${output_log})
}
