#!/sbin/openrc-run
# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="tyk"
description="tyk is an API access control"
command="/opt/bin/tyk"
command_args="--conf /etc/tyk.conf"
command_background="true"
pidfile="/var/run/${RC_SVCNAME}.pid"
output_logger="logger -p daemon.info -t ${SVCNAME}"
error_logger="logger -p daemon.error -t ${SVCNAME}"

depend() {
    after net
}
